general:
    debug : False

search:
    safe_search : 0
    autocomplete : 0

server:
    port : 11111
    bind_address : 127.0.0.1
    secret_key : "ultrasecretkey" # change this!
    base_url : False
    image_proxy : False

ui:
    themes_path : ""
    default_theme : default
    default_locale : ""

outgoing:
    request_timeout : 1.0 # seconds
    useragent_suffix : ""

engines:
  - name : general_dummy
    engine : dummy
    categories : general

  - name : dummy_dummy
    engine : dummy
    categories : dummy

locales:
    en : English
    hu : Magyar
